import { getDomRefs } from './core/dom.js';
import { createState } from './core/state.js';
import { bindCodeInput } from './features/code-input.js';
import { bindThemeSwatches } from './features/theme-swatches.js';
import { bindPaddingToggle } from './features/padding.js';
import { bindWindowStyle } from './features/window-style.js';
import { bindLineNumbersToggle } from './features/line-numbers.js';
import { bindModeToggle } from './features/mode-toggle.js';
import { bindResolutionSelect } from './features/resolution.js';
import { bindPasteFormat } from './features/paste-format.js';
import { bindExportMenu } from './features/export-menu.js';
import { initAuroraBackground } from './features/aurora-bg.js';
import { bindNavbarMorph } from './features/navbar-morph.js';
import { renderAll } from './ui/render.js';

const refs = getDomRefs();
const state = createState();

bindCodeInput(refs, state, renderAll);
bindThemeSwatches(refs, state, renderAll);
bindPaddingToggle(refs, state, renderAll);
bindWindowStyle(refs, state, renderAll);
bindLineNumbersToggle(refs, state, renderAll);
bindModeToggle(refs, state, renderAll);
bindResolutionSelect(refs, state);
bindPasteFormat(refs, state, renderAll);
bindExportMenu(refs, state);
bindNavbarMorph();
initAuroraBackground(refs.shaderBg);
renderAll(refs, state);
